# Generated by Django 5.1.2 on 2026-05-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('spectrogram', models.ImageField(blank=True, upload_to='spectrograms/')),
                ('emotion', models.CharField(blank=True, max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('all_probs', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
